### ISSUE TITLE
Ability to pre-define the pingfederate console admin password through a docker env variable. 

### ISSUE THREAD

**Issue by Diggs27** [pingidentity/pingidentity-devops-getting-started#104]
**Is your feature request related to a problem? Please describe.**
When orchestrating  Pingfederate containers, the console is pre-defined with a default admin password. To my knowledge there is no known public api endpoint that lets us change the password through automation. This creates manual effort to change the default password every time a container is orchestrated. 

**Describe the solution you'd like**
Create a docker environment variable that allows us to pass a predefined password. Or expose a tool that allows us to generate the hash of the password and send it in the container. The process would feed the pingfederate-admin-user.xml which would have the password ready by the time the container starts

**Describe alternatives you've considered**
Alternative solution #1: Expose and API to allow us to change password once Pingfed console is up and API can start handling requests. To my knowledge no known API exists. Checked pings documentation as well as explored the /pf-admin-api/api-docs.
Alternative solution #2: Allow administrators to use a tool to hash a users password that can be imported into the pingfederate-admin-users.xml file. This could be similar to the obfuscate.sh script.

**Comment by hendersj** [comment]
FYI, in PingFederate 10.1 (and probably earlier versions), the /administrativeAccounts/{username}/resetPassword API endpoint will let you programmatically reset the administrator password if you're using the native administrative accounts.

The devops images also allow you to use a pre-defined server profile that has the password already set.  Getting a profile out of a running PingFederate instance is pretty easy - what I do is export a configuration archive and feed that into the devops image 'in' structure.  The devops image will use that if no configuration is found in the 'out' structure.

**Comment by gmorgan-ping** [comment]
This feature request is being actioned in our upcoming sprint. I'll follow up once released and provide link to usage documentation

**Comment by samir-gandhi** [comment]
This issue has been determined to not provide enough value for the investment. The reason is, there are too many options for how the PF admin account can be configured (native, LDAP, oidc/sso), and it affects the bulk-import process as well. 

if you want the feature in your own deployment, I'd suggest adding a hook to your profile/image. https://pingidentity-devops.gitbook.io/devops/config/hooks#using-pre-and-post-hooks
