### ISSUE TITLE
Cannot clone/checkout on Windows:  Bad filenames

### ISSUE THREAD

**Issue by ttelford** [pingidentity/pingidentity-devops-getting-started#107]
**Describe the bug**
Windows doesn't allow filenames to contain certain characters which are allowed in Linux. There are several files which are invalid on NTFS, and as a result, users can't checkout branches with the files.

**To Reproduce**
1. Go to a Windows Machine
2. Clone pingidentity-devops-getting-started:

		$ git clone git@github.com:pingidentity/pingidentity-devops-getting-started.git	Cloning into 'ap126177-pingidentity-devops-getting-started'...
		remote: Counting objects: 9539, done.
		remote: Compressing objects: 100% (4413/4413), done.
		remote: Total 9539 (delta 5908), reused 7957 (delta 4751)
		Receiving objects: 100% (9539/9539), 18.10 MiB | 1.59 MiB/s, done.
		Resolving deltas: 100% (5908/5908), done.
		error: unable to create file docs/docker-images/ldap-sdk-tools/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingbase/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingdatagovernance/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingdatasync/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingdelegator/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingdirectoryproxy/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingdownloader/hooks/*.md: Invalid argument
		error: unable to create file docs/docker-images/pingfederate/hooks/*.md: Invalid argument
3. Note the errors complaining about files named `*.md` The `*` character is literal, and files named `*.md` are created on a Linux filesystem.

**Expected behavior**
I'd expect to be able to `git clone <repo>` and checkout the `master` branch

**Screenshots**

**Environment:**
 - Github Repo:  pingidentity-devops-getting-started
 - Docker Container: N/A:  This is an error due to the way the files are named in git.
 - Cloud Environment: N/A:  This is an error due to the way the files are named in git.

**Additional Info**
* See (This link](https://brendanforster.com/notes/fixing-invalid-git-paths-on-windows/)
* Deleting the files that are literally named `*.md` resolves the issue.

**Comment by tsigle** [comment]
Hey Troy,  Good catch here.  We have a script that creates these in an automated way.  I'll make sure to look and fix. 

tls

**Comment by tsigle** [comment]
The *.md files have been removed and the process resolved that created them in the first place.

Thanks for bring this issue up.

tls
