### ISSUE TITLE
[PingFederate] Create Process for Major Version Upgrades

### ISSUE THREAD

**Issue by dkolb** [pingidentity/pingidentity-devops-getting-started#108]
**Is your feature request related to a problem? Please describe.**
There is no documentation around using the PingFederate containers to run upgrades.  Furthermore, while the upgrade utility is included in the containers, their default setup runs contrary to expectations made by the upgrade utility.

**Describe the solution you'd like**
A well developed process for upgrading a server profile between major versions.  This solution would ideally be as automated as possible with the output being only the files necessary for a server profile.

**Describe alternatives you've considered**
Currently we have scripted a process that goes as far as:

1. Taking a server profile as input
1. Constructing a full PF_HOME using the container of the current, old version of PingFederate. We set the `STARTUP_COMMAND` to `/bin/true` so instead of starting the server the image just exits once it's completed the work of building out a full PF_HOME in `/opt/out/instance`.
1. Mounting that PF_HOME into a lightly customized PingFederate container of the new version
1. Running the upgrade utility against the old PF_HOME and having the new PF_HOME in /opt/out mounted to the host for review.

At this point we have to manually go through and only copy over the files that already exist in the server profile and work through the manual changes in the Upgrade Guide.

The lightly customized container involves

1. Adding the `bash` package
1. Stubbing out the license check hook
1. Setting the `SERVER_HOME` to `/opt/out/pingfederate` since the upgrade utility requires both the source and destination directories to be named `pingfederate`.  The defaults use a directory named `instance`.
1. Setting the `STARTUP_COMMAND` to a script that navigates to `/opt/out/pingfederate/upgrade/bin` and runs the `upgrade.sh` script with the appropriate arguments.

**Additional context**
I've set up a git repo with minimal example of our work.  You will have to provide a server profile in `mounts/profile_in` to get it working.

https://github.com/dkolb/pingfederate-upgrade

**Comment by arnaudlacour** [comment]
the message for the missing SERVER_ROOT is misleading. This is how the container detects whether it is starting for the first time versus a restart:
```
if test -d "${SERVER_ROOT_DIR}"
then
    echo "Found SERVER_ROOT: ${SERVER_ROOT_DIR}"
    RUN_PLAN="RESTART"
else
    echo "Missing SERVER_ROOT: ${SERVER_ROOT_DIR}"
    RUN_PLAN="START"
fi
```

**Comment by dkolb** [comment]
Closing as documentation now has an upgrade process.  (https://devops.pingidentity.com/how-to/upgradePingfederate/)
