### ISSUE TITLE
Integration with AWS ALB

### ISSUE THREAD

**Issue by trunal-vinerkar** [pingidentity/pingidentity-devops-getting-started#112]
**Is your feature request related to a problem? Please describe.**
I haven't seen Ping documentation to expose PingFederate services in EKS using AWS ALB

**Describe the solution you'd like**
I would like to see Ping recommendation on how to expose PingFederate engine services to internet using AWS ALB as we would like to leverage AWS WAF capabilities.

I see there are multiple options and would like to see Ping recommendation on the challenges and limitations.
1.	Use ALB ingress controller – This supports ALB. However it support backend services of type node port. Ping K8 services are of type ClusterIP.
2.	Use nginx service type external – This will point to existing ALB.

![ALB](https://user-images.githubusercontent.com/65042276/82484636-3570f580-9aa8-11ea-9d7b-d20da43e768d.PNG)

**Additional context**

**Comment by samir-gandhi** [comment]
I've added answers to your questions within [our documentation](https://pingidentity-devops.gitbook.io/devops/deploy/deployk8s/deployk8sgeneral#expose-the-applications) as well as some simple ingress examples [here](https://github.com/pingidentity/pingidentity-devops-getting-started/tree/master/20-kubernetes/10-ingress)

**Comment by trunal-vinerkar** [comment]
Thanks Samir.  These examples are helpful. However we cannot use nginx as it supports NLB.  Our security team has recommended to use WAF  which requires ALB. I am going to try AWS ALB ingress controller. It would be helpful if there is recommendation from Ping to support this requirement.

**Comment by samir-gandhi** [comment]
Nginx can use ALB as well. There shouldn't be any show-stoppers with using ALB ingress controller. I know of folks using it. 

you'll need to go with _just_ nodeport or direct load balancer for PingDirectory though. 

what other recommendations are you looking for?

**Comment by trunal-vinerkar** [comment]
Thanks Samir.
Will you be able to share example to integrate nginx with AWS ALB?
I understand it supports elb or nlb.
I am fine to use with ALB ingress controller but I am also aware about the limitation of ALB ingress per ingress.

**Comment by samir-gandhi** [comment]
You're right, I was mixing up layer 7 ELB. 
closing issue for now, we can open a new if there is anything that stops us from using ALB ingress controller.
