### ISSUE TITLE
PD Pods LDAP & LDAPS ports 

### ISSUE THREAD

**Issue by trunal-vinerkar** [pingidentity/pingidentity-devops-getting-started#114]
I am following the documentation described in this below link.

https://pingidentity-devops.gitbook.io/devops/deploy/deployk8s/deployk8spd-clusters

I have setup replication between the PD pods in one EKS cluster. Works well.

Trying to understand why ports are different for each PD pod.

I would like to keep same ports for each PD pod.

Am I missing anything?

**Comment by samir-gandhi** [comment]
Glad to hear about replication in one cluster. 

Regarding the document you mentioned, it is showing two different approaches to achieving replication across two k8s clusters. In the example where ports are changing (single load-balancer), this is only referring to the replication port, it wouldn't affect the way clients interact with PingDirectory. 

If you're looking for more on a single cluster example use: https://pingidentity-devops.gitbook.io/devops/deploy/deployk8s/deployk8sgeneral/deployk8sreplicated

Also, for general questions, you can always reach our team at devops_program@pingidentity.com

**Comment by trunal-vinerkar** [comment]
Hi Samir

I am able to setup replication between PD PODs in one EKS cluster. As mentioned earlier, due to limitation of EBS volume available in 1 AZ, I am testing the below scenario.


  1.  PD POD1 – Node 1, AZ1, EBS Volume1 ,

PD POD 2, Node 2, AZ2, EBS Volume 2



  1.  Drain Node 1. PD POD1 gets evicted and scheduler tries to reschedule PD POD1 in node 2


Issue: POD 1 events
pod didn't trigger scale-up (it wouldn't fit if a new node is added): 1 node(s) had volume node affinity conflict

Really looking forward to know if there is resolution or else we have rethink abt pd in the cluster.


Sent from my Samsung Galaxy smartphone.



-------- Original message --------

**Comment by samir-gandhi** [comment]
Hey, I believe we resolved this via email and setting "waitForFirstConsumer" on the storage class. Could you confirm?

**Comment by samir-gandhi** [comment]
closing as we will continue on email as needed
