### ISSUE TITLE
PingFederate admin console login failure

### ISSUE THREAD

**Issue by chengchengmu** [pingidentity/pingidentity-devops-getting-started#130]
**Describe the bug**
Login to https://localhost:9999/pingfederate/app fails without error message in the browser and redirects to https://localhost:9999/pingfederate/app?service=page/login

Note that https://localhost:9999/pf-admin-api/api-docs/ works: can use the APIs

**To Reproduce**
1. Deploy https://github.com/pingidentity/pingidentity-devops-getting-started/tree/master/11-docker-compose/00-standalone/pingfederate commit 8068051e65707be248e79b482f6545719ce472d3 with pingfederate docker image: 10.1.0
2. https://localhost:9999/pingfederate/app?service=page/login
3. Enter username and password, press enter

**Expected behavior**
It should successfully log in the admin console

**Environment:**
 - Github Repo: https://github.com/pingidentity/pingidentity-devops-getting-started/tree/master/11-docker-compose/00-standalone/pingfederate commit 8068051e65707be248e79b482f6545719ce472d3
 - Docker Container: pingidentity/pingfederate:10.1.0
 - Cloud Environment: Laptop CentOs 7

**Additional Info**
Logs pingfederate:
pingfederate_1  | 2020-07-31 05:22:02,012  INFO  [com.pingidentity.fsm.SessionTimeout] Application '/pingfederate' session timeout is 30 minutes.

**Comment by samir-gandhi** [comment]
Hi, 
I've tested the steps and was unable to reproduce. I was able to log in to the admin console. 

Some thoughts: 
1. there is a local docker volume that mounts pf runtime:
```
    volumes:
      - pingfederate-out:/opt/out
```

if you don't need this volume you can reset the whole stack with:
```
docker-compose down
docker volume rm pingfederate_pingfederate-out
```

2. Do pingfederate container logs show anything when you log in? 
you can also exec into the container and look at logs there. 
```
docker container exec -it pingfederate_pingfederate_1 sh

> cd /opt/out/instance/log/
> cat admin.log 
```

**Comment by chengchengmu** [comment]
Hello @samir-gandhi ,

Thanks for looking at the issue.
It is definitely an environment problem on my side: I updated docker and my browser, now I can access the admin console.
Thank you !
