### ISSUE TITLE
Ability to add autocomplete to zsh or other shells.

### ISSUE THREAD

**Issue by jrich902** [pingidentity/pingidentity-devops-getting-started#141]
**Is your feature request related to a problem? Please describe.**
Hey After running the `ping-devops config` it seems all the autocomplete scripts are set up to only install in the .bash_profile.

**Describe the solution you'd like**

I would like the option to target the file that the aliases are added to, or have some check that looks at what shell has executed `ping-devops config` then offer to add the aliases to that shells config file.

I know there are other popular shells out there like fish, perhaps support it as well would be helpful.

**Describe alternatives you've considered**
I could just let `ping-devops config` install the aliases to the .bash_profile, then copy the required changes over to my .zshrc. 

**Additional context**
not really a big issue more a nice to have 😸

**Comment by arnaudlacour** [comment]
ping-devops deprecated.
