### ISSUE TITLE
Ingress setup for PingFederate in Standalone deployment

### ISSUE THREAD

**Issue by ilhaan** [pingidentity/pingidentity-devops-getting-started#144]
**Describe the bug**
Followed steps [here](https://pingidentity-devops.gitbook.io/devops/deploy/deployk8s/deployk8sgeneral/deployk8sstandalone) to set up a standalone deployment of PingFederate in a Kubernetes cluster. Service, Deployment and ConfigMap (shown [here](https://github.com/pingidentity/pingidentity-devops-getting-started/tree/master/20-kubernetes/01-standalone/pingfederate)) were successfully created. I then tried to create an Ingress object to expose PingFederate outside the cluster based on instructions from [here](https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/docs/deployK8sGeneral.md#expose-the-applications). Ingress object was successfully created, however it does not work as expected as it results in a `ERR_SSL_PROTOCOL_ERROR` on a web browser. 

I created a custom server profile using the ["modify a server profile using local directories" ](https://pingidentity-devops.gitbook.io/devops/config/containeranatomy/profiles#modify-a-server-profile-using-local-directories) method with the following configs: 
* Added a TLS cert for the domain I intend to use in pkcs12 format. I don't typically upload TLS certs into a container and usually define required TLS cert in my ingress definition yaml, but gave this a shot to try and solve my issue to no avail. 
* Updated "Virtual Hostnames" configs (System > Virtual Hostnames) to include the two hostnames in [`pingfederate-standalone-ingress.yaml`](https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/20-kubernetes/10-ingress/pingfederate-standalone-ingress.yaml). These were `pingfederate-admin.k8s.ilhaan` and `pingfederate.k8s.ilhaan` for me. 
* Updated "Redirect Validation" configs (Security > Redirect Validation) by editing the "Valid Domain Name (leading wildcard '*.' allowed)" field to be `*.k8s.ilhaan` and unchecking the "Require HTTPS" box. Goal with this config change is to have TLS handled by the Ingress object instead of the the PingFederate container (as is standard for kubernetes deployments). 

After making the above mentioned changes, I built a Docker image using instructions from ["Built into the image - Server Profile Anatomy"](https://pingidentity-devops.gitbook.io/devops/config/containeranatomy) and re-deployed the Service, Deployment and ConfigMap. I used `kubectl port-forward <pod-name> 9999:9999` and navigated to `https://localhost:9999/pingfederate/app` and logged in to verify config changes mentioned above. 

I then created Ingress using [`pingfederate-standalone-ingress.yaml`](https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/20-kubernetes/10-ingress/pingfederate-standalone-ingress.yaml) with various config options: 
* With TLS cert from Kubernetes secrets. I have the same cert I uploaded to the PingFederate container available in k8s (this is what I use for all other application ingresses). 
* Without TLS configs - I removed the `tls` config block from the ingress file (lines 30-37) to attempt creating the Ingress object without HTTPS in order to debug the issue. 

None of the above mentioned Ingress configurations worked. 

**Expected behavior**
Use Ingress endpoint to access PingFederate UI. 

**Environment:**
 - Github Repo: https://github.com/pingidentity/pingidentity-devops-getting-started/tree/master/20-kubernetes
 - Docker Container: `pingfederate:10.1.0`
 - Cloud Environment: On-prem, Using Rancher managed Kubernetes cluster 

**Questions**
* How do I use Ingress objects to expose PingFederate outside my k8s cluster? 
* Have I missed any other PingFederate specific configs in the server profile I created?

**Comment by samir-gandhi** [comment]
Hi @ilhaan, thanks for such a detailed message and spending so much effort in our work. 
I believe the source of the issue is going to be around the configuration of your ingress-controller. 

If you followed the examples directly when creating the ingress-controller, then I think it may not work in your environment. 
Both of the examples we have for an ingress-controller is specific to AWS. The part that would be a challenge in an on-prem rancher cluster would that these ingress-controllers (Nginx or AWS) expect to would with an AWS Load Balancer. Also, this ingress exposure expects a DNS service (like Route53) to alias the hostname and point load-balancer. So the flow is like:
client app> hostname.com>aws LB (or Google/Azure)>ingress-controller>ingress>service>pod

A few thoughts I have:
1. just to check if your PingFed deployment is up and running, you can use [Kubectl Port-Forward](https://kubernetes.io/docs/tasks/access-application-cluster/port-forward-access-application-cluster/). 
```
kubectl port-forward service/pingfederate 9999:9999
```
(and in another shell/terminal)
```
kubectl port-forward service/pingfederate 9031:9031
```
2. Typically with Rancher on-prem, I have seen folks do [node-port exposure for applications](https://rancher.com/docs/rancher/v2.x/en/v1.6-migration/expose-services/#nodeport).

I may have made too many assumptions here. let me know. thanks.

**Comment by ilhaan** [comment]
Hi @samir-gandhi, thanks for the response.

* Ingress controllers in my cluster were set up by Rancher. I did not need to use the Nginx ingress-controller setup shown [here](https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/docs/deployK8sGeneral.md#pre-requisite) since Rancher took care of this for me. I have several other applications exposed using the same ingress controller in the same cluster and have appropriate DNS configs to work with ingress controllers. 
* I have verified that the PingFed deployment is up and running using the `kubectl port-forward` method and have been able to access the PingFed web interface this way. 
* I understand that certain Rancher on-prem installations require node-port exposure, but that is not the case with my cluster given that I have several other applications exposed via ingress. 

Any PingFed configs I can change/toggle to test a scenarios where Ingress controllers handle SSL termination? This is not very clear in documentation.

**Comment by samir-gandhi** [comment]
You can add a tls crt/key to pingfederate so the product itself presents it, perhaps if you want to do ssl-passthrough. But even with the default presented cert, this shouldn't interfere with an ingress configuration.

If you're using default settings, or one of our profiles, your backend protocol should be HTTPS. If you didn't want this you could use http and make the change for the admin http listener in `/instance/bin/run.properties`

**Comment by ilhaan** [comment]
Ok I managed to get past this issue by adding the cert to a customized docker container and using the same cert in the ingress object. Thanks for you help @samir-gandhi! 

Also, super excited to see activity [PingIdentity's Helm Chart repo](https://github.com/pingidentity/helm-charts)!
