### ISSUE TITLE
Custom SigningKeys are not loading

### ISSUE THREAD

**Issue by dnitsch** [pingidentity/pingidentity-devops-getting-started#159]
**Describe the bug**

SigningKeys added via the GUI and then exported configuration when re-deployed does not list them. neither updated connections are able to find it.

`Not a BUG (neither a feature request).`

**To Reproduce**

1. Add Signing Key 
2. Update a connection with that signing key
3. export configuration archive
4. re-reploy updated `instance/server/default/data`

**Expected behavior**

* See the additional signingKey in the list after redeploy with updated /opt/in data.

* Connections to be able to use that signingKey

**Environment:**
 - Github Repo: cloned locally [from](https://github.com/pingidentity/pingidentity-docker-builds/releases/tag/2008)
 - Docker Container: pingfederate `pingidentity/pingfederate:10.1.0-alpine-edge`
 - Cloud Environment: EKS (AWS)
     * Docker build

**Additional Info**

I can see an entry added in this file

`instance/server/default/data/config-store/org.sourceid.config.CoreConfig.xml` 

```xml
<!--Dsig keystore information: name and password-->
    <item name="DsigKeystoreName">ping-dsig.jks</item>
    <item name="DsigKeystorePassword">eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiRW1JY1UxOVdueSIsInZlcnNpb24iOiI5LjIuMC4xMCJ9.._Vc01Xs2XGCczUYA2vgnhA.56GD2bR9FsFcabI8CGadZ3cjVmWsPhkoIOMeczB2YG8.cpOanhUAV723mgT7h8EbUw</item>
    <!--Do not modify-->
    <!--Map of Dsig keystore aliases to passwords; the system uses this map
     to open private keys for generating signatures, X509
     authentication, etc. For each item, the name of the item maps
     to the alias of a private key, and the value of the item is the
     password to that particular key.-->
    <map name="DsigPrivateKeyPasswords">
        <item name="v8m5h9qrw85dgmndgv47k76xz">eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiRW1JY1UxOVdueSIsInZlcnNpb24iOiI5LjIuMC4xMCJ9..lnQoasV2J29-6KtVWlIWLQ.5of9PpT1aJtyrjWAX_LTz3SfghNxIFBLmU8_8tne0rU.FL732jjTyz1sTcAu9Msi2A</item>
        <item name="someGenVal">eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiRW1JY1UxOVdueSIsInZlcnNpb24iOiI5LjIuMC4xMCJ9..lnQoasV2J29-6KtVWlIWLQ.5of9PpT1aJtyrjWAX_LTz3SfghNxIFBLmU8_8tne0rU.FL732jjTyz1sTcAu9Msi2A</item>
    </map>
```

i.e this line
```xml
<item name="someGenVal">eyJhbGciOiJkaXIiLCJlbmMiOiJBMTI4Q0JDLUhTMjU2Iiwia2lkIjoiRW1JY1UxOVdueSIsInZlcnNpb24iOiI5LjIuMC4xMCJ9..lnQoasV2J29-6KtVWlIWLQ.5of9PpT1aJtyrjWAX_LTz3SfghNxIFBLmU8_8tne0rU.FL732jjTyz1sTcAu9Msi2A</item>
```

I am not sure what other places need changing. 

I have included the private key in JKS format in the root along with the other "keys and certs". 

Is the required workload to create an additional record here

```xml
    <item name="DsigKeystoreName">custom-dsig.jks</item>
```

and then inside the `DsigPrivateKeyPasswords` to use 
```xml
<item name="custom-dsig.jks-alias">$ping_fed_obfuscator_utility_keystore_pwd for custom-dsig.jks?</item>
```

Thanks for your help

**Comment by samir-gandhi** [comment]
are you _only_ using /opt/in? 
what I mean is, if you're sending your updated config on /opt/in, and also using SERVER_PROFILE_URL and PATH, that may likely be overwriting your /opt/in config.

**Comment by dnitsch** [comment]
@samir-gandhi , SERVER_PROFILE is disabled (not set) - see logs attached (that should be enough). Though I did notice just now that `SERVER_ROOT` is missing - not sure that's an issue or just an info message and a default set to `/opt/out/instance` ?

But just wanted to confirm the flow above is correct and that the values for the xml keys and and the actual values are correct as per the above.

Also, we seem to have some trouble generating a functioning non legacy obfuscated pwd with the obfuscate.sh with passwords containing characters like ```!``` and similar. Is there any best practice around this you can recommend (all is done in bash inside a CI container (pingfed-alpine)?

[pf-no-server-path.log](https://github.com/pingidentity/pingidentity-devops-getting-started/files/5775697/pf-no-server-path.log)

**Comment by samir-gandhi** [comment]
@chrisleggett may have some thoughts here

**Comment by jgdasilva** [comment]
If this is the public key attached to the IdP connection it is stored as part of the connection in the connection object, which is broken up into a separate file for each connection in the folder data/connections/0 (note there could be more then one numeric folder depending on number of connections). The connection are randomly numbered XML files and the signing key in one should look something like:

**Comment by jgdasilva** [comment]
Further to the connections being in separate files, there is also an index database that holds connection information. This is not exported and should not be part of your server profile. You basically want a new one to be created. Look in your server profile for a folder called index in your server profile and remove it.

This may explain why your changes don't appear to apply.
