### ISSUE TITLE
PingDirectory > PD_STATE

### ISSUE THREAD

**Issue by coryasilva** [pingidentity/pingidentity-devops-getting-started#178]
**Describe the bug**
Cannot start my PingDirectory StatefulSet.

I am running into [this condition](https://github.com/pingidentity/pingidentity-docker-builds/blame/master/pingdirectory/opt/staging/hooks/182-pre-setup.sh#L13-L46) but when I apply the suggested changes the PingDirectory PD_STATE will never be GENESIS due to ~[this logic](https://github.com/pingidentity/pingidentity-docker-builds/blob/master/pingdatacommon/opt/staging/hooks/pingdata.lib.sh#L748-L756)~ actually I think it is [because of this instead](https://github.com/pingidentity/pingidentity-docker-builds/blob/dc410a6a7e0e43155aca5f7cb4acaff630e0a6ac/pingdatacommon/opt/staging/hooks/pingdata.lib.sh#L700-L708).

I might be misunderstanding this... 

**To Reproduce**
1. Start a new single PingDirectory cluster on Kubernetes
2. kubectl logs pods/pingdirectory-0 --follow
3. Scroll down to 'CONTAINER FAILURE: Resolve issues with pingdirectory Kubernetes cluster service, and restart'
4. sh into a container
5. 
```sh
hostname
# pingdirectory-0
hostname -i
# 10.1.1.99
getent ahosts pingdirectory-0.pingdirectory-cluster
# returns nothing, but this is what _podHostname is being set to; not sure why we are appending the service name...
getent ahosts pingdirectory-cluster
# returns our pod since the service has `publishNotReadyAddresses: true`
# 10.1.1.99    STREAM pingdirectory-cluster.pingidentity-dev.svc.cluster.local
# 10.1.1.99    DGRAM  pingdirectory-cluster.pingidentity-dev.svc.cluster.local
```

**Expected behavior**
I expect the container to not be so opinionated about its perceptions of my environment, lol.  jk.  I just want to boot this puppy up.

**Environment:**
K8s, single cluster, EKS

```yml
  ORCHESTRATION_TYPE: KUBERNETES
  K8S_STATEFUL_SET_NAME: pingdirectory
  K8S_STATEFUL_SET_SERVICE_NAME: pingdirectory-cluster
```

**Architecture:**
1. `pingdirectory` service (NodePort, port 443): This is used to expose the PingDirectory REST Service
AWS ALB --> EKS Worker Node --> PingDirectory Pod (rest service)

2. `pingdirectory-cluster` service (ClusterIP: None, port 636): This is my headless service
(K8S Cluster internal; headless service)

**Comment by samir-gandhi** [comment]
Hey Cory, this is a result of some changes we had to make to PD startup for a more effective lifecycle. 
check out in our example where I updated this:
https://github.com/pingidentity/pingidentity-devops-getting-started/commit/2c54229bba32132382b04e2995c99b56b65cd785

**Comment by coryasilva** [comment]
@samir-gandhi Perfect! That is exactly how my `pingdirectory-cluster` server looks. 

But I am failing [this condition](https://github.com/pingidentity/pingidentity-docker-builds/blame/master/pingdirectory/opt/staging/hooks/182-pre-setup.sh#L25) because `_podHostname` is set to `pingdirectory-0.pingdirectory-cluster` by [this code](https://github.com/pingidentity/pingidentity-docker-builds/blob/dc410a6a7e0e43155aca5f7cb4acaff630e0a6ac/pingdatacommon/opt/staging/hooks/pingdata.lib.sh#L701-L702).

Consider the outputs below:

```sh
hostname
# pingdirectory-0
hostname -i
# 10.1.1.99
getent ahosts pingdirectory-0.pingdirectory-cluster
# returns nothing, but this is what _podHostname is being set to; not sure why we are appending the service name...
getent ahosts pingdirectory-cluster
# returns our pod since the service has `publishNotReadyAddresses: true`
# 10.1.1.99    STREAM pingdirectory-cluster.pingidentity-dev.svc.cluster.local
# 10.1.1.99    DGRAM  pingdirectory-cluster.pingidentity-dev.svc.cluster.local
```

Why is `_podHostname` being set to `pingdirectory-0.pingdirectory-cluster`?

**Comment by samir-gandhi** [comment]
we use the service name as part of the host to help when we have multi-region or multi-namespace deployments. 
if it's not returning anything, this seems like this is not set on the cluster service:
```
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
```

@tsigle may have some add'l thoughts

**Comment by coryasilva** [comment]
`spec.serviceName` on the StatefulSet was `pingdirectory` and should have been `pingdirectory-cluser`.

#@*&$^*#^$*&@#^$^@#&$*^@#^$)!@#&!@&(#^
