### ISSUE TITLE
Support SERVER_PROFILE_TAG reference in git repo

### ISSUE THREAD

**Issue by tsigle** [pingidentity/pingidentity-devops-getting-started#18]
The images, more specifically, hook ```14-get-remote-server-profile.sh``` should provide the ability to specify a git tag when getting a remote server profile.

Example, a YAML should allow for either a ```SERVER_PROFILE_BRANCH``` or a ```SERVER_PROFILE_TAG``` to be specified. 

```
      - SERVER_PROFILE_URL=https://github.com/pingidentity/server-profile-......git
      - SERVER_PROFILE_TAG=v1.1
      - SERVER_PROFILE_PATH=pingdirectory
```

In this case, the hook should:

```
    git checkout "${SERVER_PROFILE_TAG}"
```

There shouldn't be a reason for for both a TAG and BRANCH to be specified.  If they are, we should either:

1. provide precedence to 1 of them (probably TAG) <--- provably preference
2. error out

**Comment by tsigle** [comment]
I believe an option to cloning a tag with a shallow clone is:

```
# Clone a specific tag name
 git clone <url> --branch=<tag_name>
```

**Comment by arnaudlacour** [comment]
this is provided as of recent commits. The tag name must be provided via the SERVER_PROFILE_BRANCH variable.
