### ISSUE TITLE
Obfuscated password does not work in ping federate for the ldap password

### ISSUE THREAD

**Issue by jitumiah** [pingidentity/pingidentity-devops-getting-started#184]
**Describe the bug**
Obfuscating a password using `/opt/server/bin/obfuscate.sh` doesn't work when using it for the ping fed datastore(ping directory ldap type)  password. The password we used has multiple ! symbols maybe and we used the script without legacy flag. 

It doesn't seem to work without legacy flag but works with legacy flag.

**To Reproduce**
Steps to reproduce the behaviour:
1. In ping federate engine server go to `/opt/server/bin/obfuscate.sh`
2. run `/opt/server/bin/obfuscate.sh <password>` to obfuscate the password.
3. set obfuscated password for the ldap datastore in ldap.properties
4. Start/Restart ping fed
4. Ping fed will no longer be able to connect to ldap data store using obfuscated password

**Expected behavior**
Obfuscated(non legacy) password should work in ping federate for ldap password

**Screenshots**
n/a

**Environment:**

Github Repo: cloned locally from
Docker Container: pingfederate pingidentity/pingfederate:10.1.0-alpine-edge
Cloud Environment: EKS (AWS)
Docker build

**Additional Info**
n/a

**Comment by arnaudlacour** [comment]
To use the cryptographuc material in the runtime `pf.jwk` use the runtime script
`/opt/out/instance/bin/obfuscate.sh`
rather than the static
`/opt/server/bin/obfuscate.sh`

**Comment by arnaudlacour** [comment]
Let me know if you can confirm this fixed your issue.

**Comment by jitumiah** [comment]
@arnaudlacour yes that works. thank you.
