### ISSUE TITLE
Check for missing required variables in docker-build hooks

### ISSUE THREAD

**Issue by tsigle** [pingidentity/pingidentity-devops-getting-started#19]
Currently, the server-profiles can optionally provide env_vars files to be later sourced by docker-build hooks.

As an example, the variable ROOT_USER_PASSWORD_FILE is provided through this mechanism.

However, when it's used (i.e. hook - 183-run-setup.sh), the setup fails if that variable isn't set.

At a minimum, these variables should be checked and an error created.  At this point, there doesn't seem to be a need to force an env-vars file, as these variables can come in a number of different ways (i.e. env-vars, docker-run --env facility).

**Comment by arnaudlacour** [comment]
this is now taken care of by 04-check-variables.sh
