### ISSUE TITLE
Cleanup PingDataConsole default URL

### ISSUE THREAD

**Issue by tsigle** [pingidentity/pingidentity-devops-getting-started#24]
Currently, the PingDataConsole root page is the standard Apache Tomcat docs.  And the console is deployed to a location different from the standard product deployment ("/console").

In order to make the landing page more foolproof, a few things would be nice.

1. Deploy the admin-console.war to ("/console")
2. Create a 302 redirect page "index.html" redirecting the user to "/console"

**Comment by tsigle** [comment]
If we want, we could also create a 302 redirection from /admin-console/index.html to /console also for backward compatibility on any bookmarks people have.

**Comment by arnaudlacour** [comment]
I would much rather we handled this in PingAccess as there are other issues better solved there.
