### ISSUE TITLE
docker image issue - After update from 0.6.2 to 0.6.3+, PF admin image does not start on OpenShift with error "sh: can't open './bootstrap.sh': Permission denied"

### ISSUE THREAD

**Issue by gsustek** [pingidentity/pingidentity-devops-getting-started#257]
I'm  referencing in this BUG report to internal ticket, GDO-899. 

After update from 0.6.2 to 0.6.3+, pf does not start with error "sh: can't open './bootstrap.sh': Permission denied" in openshift environment. Openshift environment by default has his own range of useruid to assign for running image.
Even if yaml file is populated with below values for runAsUser it seems that only userid 9031 has the ability to start ./bootstrap.sh script!
Version 0.6.2 has this ability
Version from 0.6.3 and later does not have this ability to set arbitrary userid in /ets/passwd

####example of yaml file####
pingfederate-admin:
enabled: true
ingress:
annotations:
nginx.ingress.kubernetes.io/backend-protocol: HTTPS
defaultDomain: apps.projects.internal.local.com
enabled: false
resources:
requests:
cpu: 100m
memory: 100Mi
pingfederate-engine:
enabled: true
resources:
requests:
cpu: 100m
memory: 100Mi
global:
workload:
securityContext:
runAsUser: 1002410000
runAsGroup: 1002410000
fsGroup: 1002410000

######################

FYI: i cannot open this ticket in https://github.com/pingidentity/pingidentity-docker-builds because there is not "Issue" button to submit it. Sorry if i post it on a wrong repo...

Regards,
Goran.

**Comment by wellsjames** [comment]
We have actually made changes to our images to run properly on OpenShift by allowing any member of the _root:0_ group to be able to start our images alongside the _ping:9031_ user. You would need to remove your runAsGroup securityContext, possibly the fsGroup as well though in order to ensure proper permissions.

**Comment by gsustek** [comment]
Hi still one bug....
init container of engine still has **unconfigurable** runAsUser value 9031

`    spec:
      restartPolicy: Always
      initContainers:
        - name: wait-for-pingfederate-admin
          image: 'pingidentity/pingtoolkit:2112'
          command:
            - sh
            - '-c'
            - >-
              echo "Waiting for
              team-cpc2-pingfederate-pingfederate-admin:"9999"..." && wait-for
              team-cpc2-pingfederate-pingfederate-admin:"9999" -t 300 -- echo
              "team-cpc2-pingfederate-pingfederate-admin:"9999" running"
          resources:
            limits:
              cpu: 500m
              memory: 128Mi
            requests:
              cpu: 1m
              memory: 64Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: IfNotPresent
          securityContext:
            capabilities:
              drop:
                - ALL
            runAsUser: 9031
            runAsGroup: 0
            runAsNonRoot: true
            readOnlyRootFilesystem: true
            allowPrivilegeEscalation: false
      schedulerName: default-scheduler
      affinity: {}
      terminationGracePeriodSeconds: 30
      shareProcessNamespace: false
      securityContext:
        runAsUser: 1002970000
        runAsGroup: 0
        fsGroup: 1002970000
      containers:`

**Comment by wellthatsjames** [comment]
Is the container starting successfully? If it's not respecting the runAsUser value that should be okay based on RedHat guidance around how containers work as an arbitrary UID is selected for the container. https://cloud.redhat.com/blog/a-guide-to-openshift-and-uids provides a bit of insight, primarily under the "User ID (UID) and Containers" heading. If the container is still failing to start or function properly we can definitely reopen this and investigate further. Looking forward to hearing further.
