### ISSUE TITLE
Small Typo in Docs

### ISSUE THREAD

**Issue by jgminer** [pingidentity/pingidentity-devops-getting-started#286]
**Describe the bug**
There is a small typo in the docs - "oportunity" - https://github.com/pingidentity/pingidentity-devops-getting-started/blob/e20212c625f67ac66cf25cacb7f3da7c54df98a9/docs/get-started/k8sHelmBasics.md?plain=1#L143

**To Reproduce**
1. Go to the Helm section info https://devops.pingidentity.com/get-started/k8sHelmBasics/#helm on the live site

**Expected behavior**
Should be "opportunity"

**Comment by gmorgan-ping** [comment]
Thanks for the heads up. Changes are being pushed now.
