### ISSUE TITLE
Broken Links in README.dm

### ISSUE THREAD

**Issue by nicholas-marchini** [pingidentity/pingidentity-devops-getting-started#291]
**Describe the bug**
Some links produce a 404 in the readme here - https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/99-helper-scripts/ping-bulkconfigtool/README.md

**To Reproduce**
1. Go to https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/99-helper-scripts/ping-bulkconfigtool/README.md#examples
2. Click on any of the example files.
3. See error 404

**Expected behavior**
Clicking on the link takes to to the file example

**Comment by wesleymccollam** [comment]
@nicholas-marchini, we've deprecated this document and have moved to use another documentation page for this information. See [link here](https://github.com/pingidentity/pingidentity-devops-getting-started/blob/master/99-helper-scripts/ping-bulkconfigtool/README.md#this-document-has-been-deprecated-please-see-this-document-for-bulk-config-tool-information).
