### ISSUE TITLE
PingFederate Start Failure

### ISSUE THREAD

**Issue by vjainsimeio** [pingidentity/pingidentity-devops-getting-started#3]
Ran the command (./docker-run.sh pingfederate) as Root in the server but unable to start. 

Following is the logs entry we get from the docker image. Please let us know if any pre-requisite missed.

cp: can't create directory '/opt/out/instance': Permission denied
+ apply_server_profile
+ test -z https://github.com/pingidentity/server-profile-group-pingidentity-getting-started.git
+ git clone https://github.com/pingidentity/server-profile-group-pingidentity-getting-started.git /opt/server-profile
fatal: destination path '/opt/server-profile' already exists and is not an empty directory.
CONTAINER FAILURE: Git clone failure
+ die_on_error 78 'Git clone failure'
+ errorCode=128
+ exitCode=78
+ shift
+ test 128 -ne 0
+ echo 'CONTAINER FAILURE: Git clone failure'
+ rm -rf /opt/out/instance
+ exit 78

**Comment by tsigle** [comment]
We are currently making some changes to the images and associated server profiles.  This looks like you have an older version of the docker image in your local registry.

Can you try to remove any containers on the pingidentity/pingfederate image and then remove that image from your local registry:   

  docker image rm pingidentity/pingfederate

then cleanup any directories using the docker-cleanup.sh command

  ./docker-cleanup.sh pingfederate --force

Then, try to run the docker-run.sh again.  You should notice that a new version of the pingidentity/pingfederate is downloaded.

Reply back to this issue if this resolves itself.

**Comment by vjainsimeio** [comment]
Thanks for replying, I tried to do it and got a new error.

+ test -z https://github.com/pingidentity/server-profile-group-pingidentity-getting-started.git
+ git clone https://github.com/pingidentity/server-profile-group-pingidentity-getting-started.git /opt/server-profile
Cloning into '/opt/server-profile'...
Initializing server for the first time
+ die_on_error 14 'Git clone failure'
+ errorCode=0
+ exitCode=14
+ shift
+ test 0 -ne 0
+ test -z
+ cp -af /opt/server-profile/pingfederate/README.md /opt/server-profile/pingfederate/instance /opt/staging
+ die_on_error 14 'Error running hook 14-get-remote-server-profile.sh'
+ errorCode=0
+ exitCode=14
+ shift
+ test 0 -ne 0
+ run_if present /opt/staging/hooks/16-apply-server-profile.sh
+ mode=present
+ shift
+ runFile=/opt/staging/hooks/16-apply-server-profile.sh
+ test -z
+ test present '=' absent
+ testFile=/opt/staging/hooks/16-apply-server-profile.sh
+ test present '=' present
+ test -f /opt/staging/hooks/16-apply-server-profile.sh
+ sh -x /opt/staging/hooks/16-apply-server-profile.sh
+ test -d /opt/staging/instance
+ cp -af /opt/staging/instance /opt/out
cp: can't create directory '/opt/out/instance': Permission denied
+ die_on_error 16 'Error running hook 16-apply-server-profile.sh'
+ errorCode=1
+ exitCode=16
+ shift
+ test 1 -ne 0
+ echo 'CONTAINER FAILURE: Error running hook 16-apply-server-profile.sh'
+ rm -rf /opt/out/instance
CONTAINER FAILURE: Error running hook 16-apply-server-profile.sh
+ exit 16
+ die_on_error 10 'First time sequence failed'
+ errorCode=16
+ exitCode=10
+ shift
+ test 16 -ne 0
+ echo 'CONTAINER FAILURE: First time sequence failed'
+ rm -rf /opt/out/instance
CONTAINER FAILURE: First time sequence failed
+ exit 10

**Comment by tsigle** [comment]
You are getting the error: 

   cp: can't create directory '/opt/out/instance': Permission denied

Are you on windows or running with your out volume on a directory that doesn't have permission to write?

**Comment by vjainsimeio** [comment]
No, I am using a Linux Server. Do we have any prerequisite

**Comment by vjainsimeio** [comment]
Updated error - Same happens for all Ping products

+ test start-server '=' start-server
+ run_if present /opt/in/hooks/00-immediate-startup.sh
+ mode=present
+ shift
+ runFile=/opt/in/hooks/00-immediate-startup.sh
+ test -z
+ test present '=' absent
+ testFile=/opt/in/hooks/00-immediate-startup.sh
+ test present '=' present
+ test -f /opt/in/hooks/00-immediate-startup.sh
+ first_time_sequence
+ test '!' -f /opt/out/instance/config/server.uuid
+ echo 'Initializing server for the first time'
+ run_if present /opt/in/hooks/10-before-copying-bits.sh
+ mode=present
+ shift
+ runFile=/opt/in/hooks/10-before-copying-bits.sh
+ test -z
+ test present '=' absent
+ testFile=/opt/in/hooks/10-before-copying-bits.sh
+ test present '=' present
+ test -f /opt/in/hooks/10-before-copying-bits.sh
+ deploy_server_bits
+ test -d /opt/out/instance
+ cp -af /opt/server /opt/out/instance
cp: can't create directory '/opt/out/instance': Permission denied
Initializing server for the first time
+ apply_server_profile
+ test -z https://github.com/pingidentity/server-profile-pingdirectory-basic.git
+ git clone https://github.com/pingidentity/server-profile-pingdirectory-basic.git /opt/server-profile
fatal: destination path '/opt/server-profile' already exists and is not an empty directory.
+ die_on_error 78 'Git clone failure'
+ errorCode=128
+ exitCode=78
+ shift
+ test 128 -ne 0
+ echo 'CONTAINER FAILURE: Git clone failure'
+ rm -rf /opt/out/instance
CONTAINER FAILURE: Git clone failure
+ exit 78

**Comment by tsigle** [comment]
The Permission denied seems like some type of Docker setup issue.

My colleague wondered if Docker was added to the correct user group.  A link to that article is:

   https://docs.docker.com/install/linux/linux-postinstall/

**Comment by vjainsimeio** [comment]
Thanks for input.

I am running docker as a root user, so should have not permissions issues.

**Comment by arnaudlacour** [comment]
The issue seems to be related to SELinux preventing the docker process from writing to the path mounted to the /opt/out container volume.

[This article](https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker) may be helpful

**Comment by tsigle** [comment]
Just updating this issue with the latest from email.

Vipin's comments:

> We have made good progress within Simeio to run the PingFederate with Static Cluster for Admin/Run Time nodes using Docker.
> 
> Can we please connect on this and talk about it. Please let us know what times works for you.
