### ISSUE TITLE
Documentation error - conflict markers present in text

### ISSUE THREAD

**Issue by ahaeber** [pingidentity/pingidentity-devops-getting-started#322]
**Describe the bug**
The documentation at https://devops.pingidentity.com/get-started/k8sBasics/ looks a bit weird because it includes what appears to be a merge conflict that was commited.

**To Reproduce**
1. Go to https://devops.pingidentity.com/get-started/k8sBasics/
2. See conflict markers "<<<<<<< HEAD:docs/get-started/k8sHelmBasics.md" various places.

**Expected behavior**
Documentation without conflict markers.

**Screenshots**
Notice the conflict marker `<<<<<<< HEAD:docs/get-started/k8sHelmBasics.md ` is present in the document:
![image](https://user-images.githubusercontent.com/849280/156442122-01b9455e-498f-4b90-aec0-29a4c8b55666.png)

![image](https://user-images.githubusercontent.com/849280/156442887-a5842dff-f7c6-4d6c-8e30-d60a8fd24630.png)

![image](https://user-images.githubusercontent.com/849280/156442926-1bad4086-7db2-4c48-b892-111cbb6c2c78.png)

**Environment:**
 - Github Repo: [e.g. pingidentity-devops, server-profile, docker-builds]
 - Docker Container: [e.g. pingfederate, pingdirectory, ...]
 - Cloud Environment: [e.g. host OS, AWS, Azure, Google]

**Additional Info**
It appears that this change was introduced in PR #319 (https://github.com/pingidentity/pingidentity-devops-getting-started/pull/319)

**Comment by marcodelas** [comment]
Hello Andreas, thank you for bringing up this issue. The documentation has been cleaned up.
