### ISSUE TITLE
PF sign SAML Assertion with expired sign certificate

### ISSUE THREAD

**Issue by gsustek** [pingidentity/pingidentity-devops-getting-started#362]
**Describe the bug**
PF signs SAML Assertion with expired sign certificate

**Expected behavior**
Not to do sign if it expired

**Screenshots**

**Environment:**

 - Docker Container: [e.g. pingfederate, pingdirectory, ...]

**Additional Info**
{"@timestamp":"2022-06-14T14:22:51.493+02:00","sequence":242,"log.logger.name":"org.jboss.logging.Logger","log.logger":"com.adcubum.syrius.security.idp.sso.saml.tokenexchange.SamlWithTokenExchangeIdentityProvider","log.level":"DEBUG","message":"SAML token exchange failed","process.thread.id":"default task-4","process.thread.name":198,"mdc":{},"ndc":"","host.hostname":"rhsso-application-mock-env-6946884cd9-8fdsk","process.name":"jboss-modules.jar","process.pid":676,"error.stack_trace":": java.security.cert.CertificateExpiredException: NotAfter: Sat Jun 11 17:20:47 CEST 2022\n\tat java.base/sun.security.x509.CertificateValidity.valid(CertificateValidity.java:277)\n\tat java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:675)\n\tat java.base/sun.security.x509.X509CertImpl.checkValidity(X509CertImpl.java:648)\n\tat deployment.sso-saml-tokenexchange-extension-0.5.0.jar//com.adcubum.syrius.security.idp.sso.saml.tokenexchange.SamlWithTokenExchangeIdentityProvider.getIdpKeyLocator(SamlWithTokenExchangeIdentityProvider.java:241)\n\tat deployment.sso-saml-tokenexchange-extension-

**Comment by pingone-davinci** [comment]
This is the expected behavior, PingFederate will sign the assertion with the expired certificate and it is up to the SP to verify that the assertion was signed with a valid certificate upon reception.
