### ISSUE TITLE
Docs instruction to clone pingidentity-server-profiles should state forked version

### ISSUE THREAD

**Issue by jgdasilva** [pingidentity/pingidentity-devops-getting-started#41]
**Describe the bug**
The instructions in the getting started in step 3 should have you clone the forked version that was created in step 2.

**To Reproduce**
1. Review steps as documented [here](https://pingidentity-devops.gitbook.io/devops/server-profiles/quickstart).

**Expected behavior**
Make the step clearer that the forked version should be used. 

**Screenshots**
Not applicable.

**Environment:**
 - Github Repo: pingidentity-devops-getting-started
 - Docker Container: pingfederate
 - Cloud Environment: NA

**Additional Info**
None.

**Comment by gmorgan-ping** [comment]
Thanks @jgdasilva for the feedback! I've updated the messaging to hopefully make it more clear
