### ISSUE TITLE
ping-bulk-config tool add-config ignores paths with multiple slashes

### ISSUE THREAD

**Issue by samir-gandhi** [pingidentity/pingidentity-devops-getting-started#424]
**Describe the bug**
The bulk-config-tool seems to ignore adding paths that have multiple slashes.

**To Reproduce**
1. get a data.json, set up env as described in [docs](https://devops.pingidentity.com/how-to/buildPingFederateProfile/#using-bulk-config-tool). 
example of relevant section of data.json:
```
    {
      "resourceType": "/idp/spConnections",
      "operationType": "SAVE",
      "items": [
        {}
      ]
    },
```
2. config.json

```json
{
  "add-config": [
    {
      "resourceType": "/idp/spConnections",
      "item": {
        "foo": "bar"
      }
    }
  ],
  "config-aliases": [],
  "remove-config": [],
  "expose-parameters": []
}
```

run command:
```
docker run --rm -v /tmp/pftest/shared:/shared ping-bulkconfig /shared/config.json /shared/data.json /shared/env_vars /shared/data.json.subst > shared/output.log
```

**Expected behavior**
output of relevant section data.json.subst should be: 
```json
        {
            "operationType": "SAVE",
            "items": [{"foo": "bar"}],
            "resourceType": "/idp/spConnections"
        },
```

This is effectively the same as our default example in docs. working with a resource without multiple slashes (like /redirectValidation) works just fine. 
In fact, even just removing the second slash from "/idp/spConnections" on data.json and config.json works

**Comment by samir-gandhi** [comment]
@ttranatping would you mind taking a look into this?

**Comment by PingDavidR** [comment]
reviving this for resolution/inquiry, @ttranatping

**Comment by ttranatping** [comment]
Hi - will look into it today/tomorrow.

**Comment by ttranatping** [comment]
I've resolved the processAddConfig issue and merged it into master @samir-gandhi @PingDavidR

**Comment by PingDavidR** [comment]
Thanks @ttranatping !
