### ISSUE TITLE
PingDirectoryProxy topology feature broken

### ISSUE THREAD

**Issue by jsolares-nfl** [pingidentity/pingidentity-devops-getting-started#468]
**Describe the bug**
The script 80-post-start.sh in PingDirectoryProxy docker images has the wrong values for pod port and hostname, they are switched

**To Reproduce**
1. Enable JOIN_PD_TOPOLOGY: "true"

**Expected behavior**
Joins the topology

**Error**
manage-topology add-server --retryTimeoutSeconds 180 --trustAll --hostname 1636 --port pingdirectoryproxy-0 --useSSL --bindDN 'cn=administrator' --bindPasswordFile /opt/staging/.sec/root-user-password --remoteServerHostname pingdirectory-0.identity.ext.lv1low.dm.nfl.com --remoteServerPort 1636 --remoteServerConnectionSecurity useSSL --remoteServerBindDN 'cn=administrator' --remoteServerBindPasswordFile /opt/staging/.sec/root-user-password --adminUID admin --adminPassword 2FederateM0re --ignoreWarnings
/opt/out/instance/bin/../lib/_client-script.sh: /opt/out/instance/lib/_script-util.sh: line 185: test_crlf: not found
/opt/out/instance/bin/../lib/_client-script.sh: /opt/out/instance/lib/_script-util.sh: line 186: die_on_error: not found
/opt/out/instance/bin/../lib/_client-script.sh: /opt/out/instance/lib/_script-util.sh: line 44: test_crlf: not found
/opt/out/instance/bin/../lib/_client-script.sh: /opt/out/instance/lib/_script-util.sh: line 45: die_on_error: not found

**Code issue**
manage-topology add-server \
    --retryTimeoutSeconds "${RETRY_TIMEOUT_SECONDS}" \
    --trustAll \
    **--hostname "${POD_LDAPS_PORT}" \**
    **--port "${POD_HOSTNAME}" \**
    --useSSL \
    --bindDN "${ROOT_USER_DN}" \
    --bindPasswordFile "${ROOT_USER_PASSWORD_FILE}" \
    --remoteServerHostname "${PINGDIRECTORY_HOSTNAME}" \
    --remoteServerPort "${PINGDIRECTORY_LDAPS_PORT}" \
    --remoteServerConnectionSecurity useSSL \
    --remoteServerBindDN "${ROOT_USER_DN}" \
    --remoteServerBindPasswordFile "${ROOT_USER_PASSWORD_FILE}" \
    --adminUID "${ADMIN_USER_NAME}" \
    --adminPassword "${ADMIN_USER_PASSWORD}" \
    --ignoreWarnings

**Environment:**
 - Github Repo: docker-builds
 - Docker Container: pingdirectoryproxy
 - Cloud Environment: local k8s cluster

**Comment by timothynguyen90** [comment]
@jsolares-nfl Thank you for bring up this issue. We have updated the code base with the fix
