### ISSUE TITLE
PingFederate:11.2.7-latest container not loading license file on Red Hat OpenShift Local

### ISSUE THREAD

**Issue by ADAMSRD** [pingidentity/pingidentity-devops-getting-started#509]
**Describe the bug**
I am following instructions in https://devops.pingidentity.com/how-to/existingLicense/
to mount an existing license file.  However, the pod goes to crashloopback with error:
          ----- Starting hook: /opt/staging/hooks/17-check-license.sh
          A license file was not provided at the expected location: /opt/out/instance/server/default/conf/pingfederate.lic
          No credentials were provided to retrieve an evaluation license.
          ##################################################################################
          ############################ ALERT #################################
          ##################################################################################
          #
          # License File could not be found at the expected location
          # /opt/out/instance/server/default/conf/pingfederate.lic
          # An evaluation license could not be obtained from PingIdentity either.
          #
          #
          # More info on obtaining your DevOps User and Key can be found at:
          # https://devops.pingidentity.com/how-to/devopsRegistration/
          #
          ##################################################################################
          CONTAINER FAILURE: License File absent

**To Reproduce**
1. Red Hat OpenShift Local
2. Use image pingfederate:11.2.7-latest (tried with 11.3 also without success)

**Expected behavior**
The container should mount the license to /opt/in and copy to /opt/out; PingFederate should start without error.

**Environment:**
 - Red Hat OpenShift Local
 - image pingfederate:11.2.7-latest

Followed instructions here also, without success:
https://github.com/pingidentity/pingidentity-devops-getting-started/issues/132

YAML:

spec:
  volumes:
    - name: pingfederate-license-volume
      secret:
        secretName: pingfederate-license
        defaultMode: 420
  containers:
    - name: pingfederate
      image: >-
        image-registry.openshift-image-registry.svc:5000/pingfederate/pingfederate@sha256:491c667f1223509c91fc5f95296989a746db086f1f368a42b4c02f1a58a3c70f
      ports:
        - containerPort: 9031
          protocol: TCP
        - containerPort: 9999
          protocol: TCP
      resources: {}
      volumeMounts:
        - name: pingfederate-license-volume
          mountPath: /opt/in/instance/server/default/conf/pingfederate.lic

**Comment by ADAMSRD** [comment]
I've added my PING_IDENTITY_DEVOPS_USER and PING_IDENTITY_DEVOPS_KEY to the Environment Variables and now getting this in the logs:

                
                
                [0;32m----- Starting hook: /opt/staging/hooks/17-check-license.sh[0m
                A license file was not provided at the expected location: /opt/out/instance/server/default/conf/pingfederate.lic
                We will now attempt to retrieve an evaluation license.
                Pulling evaluation license from Ping Identity for:
                   Prod License: PF - v11.2
                    DevOps User: {MyUserAccount}...
                curl: (23) Failure writing output to destination
                curl: (23) Failure writing output to destination
                curl: (23) Failure writing output to destination
                curl: (23) Failure writing output to destination
                
                Unable to download evaluation license:
                         Reason: Error (http code: 200 exit code: 23). Ping Identity customers can create a case in the [Ping Identity Support Portal](https://support.pingidentity.com/s/)
                 with this log. Non-Ping Identity customers can use the [PingDevOps Community](https://support.pingidentity.com/s/topic/0TO1W000000IF30WAG/pingdevops) for questions.
                rm: '/opt/out/instance/server/default/conf/pingfederate.lic' is a directory
                [0;31m[0m
                [0;31m##################################################################################[0m
                [0;31m############################        ALERT        #################################[0m
                [0;31m##################################################################################[0m
                [0;31m#[0m
                [0;31m# License File could not be found at the expected location[0m
                [0;31m# /opt/out/instance/server/default/conf/pingfederate.lic[0m
                [0;31m# An evaluation license could not be obtained from PingIdentity either.[0m
                [0;31m#[0m
                [0;31m#[0m
                [0;31m# More info on obtaining your DevOps User and Key can be found at:[0m
                [0;31m#      https://devops.pingidentity.com/how-to/devopsRegistration/[0m
                [0;31m#[0m
                [0;31m##################################################################################[0m
                [0;31mCONTAINER FAILURE: License File absent[0m

**Comment by ADAMSRD** [comment]
OK, I got the license to pull using my user/key.  It appears PingFed doesn't like having both the volume mount AND the environment variables.  Once I cleaned that up, the container accepted the env vars.  I also had to add PING_IDENTITY_ACCEPT_EULA=YES to the env vars.

**Comment by PingDavidR** [comment]
Thanks @ADAMSRD for sharing this with us.  I was preparing to investigate, but it seems you sorted things out.  I'll drop a ticket on our side to find a way to clarify the behavior you described.  I think that the mount/var issue is common across products and want to investigate before we get that out on the portal.  

Are you OK with me closing this ticket at this time?

**Comment by ADAMSRD** [comment]
I got it to work with my DevOps creds for our dev environment but I still need it to work with a license file before I can take it to Production.  Our Prod environment is offline from the Internet, so this is an important component.  I'll be testing more this evening and tomorrow.

**Comment by ADAMSRD** [comment]
Replaced the user/key with the volumeMount for the license again and back to the same problem.

This is the YAML from the Pod

![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/19368683/14d385c7-35bb-4145-bb13-deb0f481a06d)


kind: Pod
apiVersion: v1
metadata:
  generateName: pingfederate-74f9b5c667-
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "openshift-sdn",
          "interface": "eth0",
          "ips": [
              "10.217.0.66"
          ],
          "default": true,
          "dns": {}
      }]
    openshift.io/generated-by: OpenShiftWebConsole
    openshift.io/scc: restricted-v2
    seccomp.security.alpha.kubernetes.io/pod: runtime/default
  resourceVersion: '524831'
  name: pingfederate-74f9b5c667-h2h9v
  uid: 6c35eec9-abba-4451-b43d-8575c77993ff
  creationTimestamp: '2023-10-02T22:51:05Z'
  managedFields:
    - manager: kube-controller-manager
      operation: Update
      apiVersion: v1
      time: '2023-10-02T22:51:05Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            .: {}
            'f:openshift.io/generated-by': {}
          'f:generateName': {}
          'f:labels':
            .: {}
            'f:app': {}
            'f:deployment': {}
            'f:pod-template-hash': {}
          'f:ownerReferences':
            .: {}
            'k:{"uid":"484a3c7f-b306-4509-ab37-8cdf0e75793c"}': {}
        'f:spec':
          'f:containers':
            'k:{"name":"pingfederate"}':
              'f:image': {}
              'f:volumeMounts':
                .: {}
                'k:{"mountPath":"/opt/in/instance/server/default/conf/pingfederate.lic"}':
                  .: {}
                  'f:mountPath': {}
                  'f:name': {}
                  'f:subPath': {}
              'f:terminationMessagePolicy': {}
              .: {}
              'f:resources': {}
              'f:env':
                .: {}
                'k:{"name":"PING_IDENTITY_ACCEPT_EULA"}':
                  .: {}
                  'f:name': {}
                  'f:value': {}
              'f:terminationMessagePath': {}
              'f:imagePullPolicy': {}
              'f:ports':
                .: {}
                'k:{"containerPort":9031,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
                'k:{"containerPort":9999,"protocol":"TCP"}':
                  .: {}
                  'f:containerPort': {}
                  'f:protocol': {}
              'f:name': {}
          'f:dnsPolicy': {}
          'f:enableServiceLinks': {}
          'f:restartPolicy': {}
          'f:schedulerName': {}
          'f:securityContext': {}
          'f:terminationGracePeriodSeconds': {}
          'f:volumes':
            .: {}
            'k:{"name":"pingfederate-license-volume"}':
              .: {}
              'f:name': {}
              'f:secret':
                .: {}
                'f:defaultMode': {}
                'f:secretName': {}
    - manager: multus
      operation: Update
      apiVersion: v1
      time: '2023-10-02T22:51:07Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:metadata':
          'f:annotations':
            'f:k8s.v1.cni.cncf.io/network-status': {}
      subresource: status
    - manager: kubelet
      operation: Update
      apiVersion: v1
      time: '2023-10-02T22:51:32Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          'f:conditions':
            'k:{"type":"ContainersReady"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Initialized"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:status': {}
              'f:type': {}
            'k:{"type":"Ready"}':
              .: {}
              'f:lastProbeTime': {}
              'f:lastTransitionTime': {}
              'f:message': {}
              'f:reason': {}
              'f:status': {}
              'f:type': {}
          'f:containerStatuses': {}
          'f:hostIP': {}
          'f:phase': {}
          'f:podIP': {}
          'f:podIPs':
            .: {}
            'k:{"ip":"10.217.0.66"}':
              .: {}
              'f:ip': {}
          'f:startTime': {}
      subresource: status
  namespace: pingfederate
  ownerReferences:
    - apiVersion: apps/v1
      kind: ReplicaSet
      name: pingfederate-74f9b5c667
      uid: 484a3c7f-b306-4509-ab37-8cdf0e75793c
      controller: true
      blockOwnerDeletion: true
  labels:
    app: pingfederate
    deployment: pingfederate
    pod-template-hash: 74f9b5c667
spec:
  restartPolicy: Always
  serviceAccountName: default
  imagePullSecrets:
    - name: default-dockercfg-dl9ps
  priority: 0
  schedulerName: default-scheduler
  enableServiceLinks: true
  terminationGracePeriodSeconds: 30
  preemptionPolicy: PreemptLowerPriority
  nodeName: crc-lz7xw-master-0
  securityContext:
    seLinuxOptions:
      level: 's0:c26,c10'
    fsGroup: 1000670000
    seccompProfile:
      type: RuntimeDefault
  containers:
    - resources: {}
      terminationMessagePath: /dev/termination-log
      name: pingfederate
      env:
        - name: PING_IDENTITY_ACCEPT_EULA
          value: 'YES'
      securityContext:
        capabilities:
          drop:
            - ALL
        runAsUser: 1000670000
        runAsNonRoot: true
        allowPrivilegeEscalation: false
      ports:
        - containerPort: 9031
          protocol: TCP
        - containerPort: 9999
          protocol: TCP
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - name: pingfederate-license-volume
          mountPath: /opt/in/instance/server/default/conf/pingfederate.lic
          subPath: pingfederate.lic
        - name: kube-api-access-zqkqr
          readOnly: true
          mountPath: /var/run/secrets/kubernetes.io/serviceaccount
      terminationMessagePolicy: File
      image: >-
        image-registry.openshift-image-registry.svc:5000/pingfederate/pingfederate@sha256:491c667f1223509c91fc5f95296989a746db086f1f368a42b4c02f1a58a3c70f
  serviceAccount: default
  volumes:
    - name: pingfederate-license-volume
      secret:
        secretName: pingfederate-license
        defaultMode: 420
    - name: kube-api-access-zqkqr
      projected:
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              name: kube-root-ca.crt
              items:
                - key: ca.crt
                  path: ca.crt
          - downwardAPI:
              items:
                - path: namespace
                  fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
          - configMap:
              name: openshift-service-ca.crt
              items:
                - key: service-ca.crt
                  path: service-ca.crt
        defaultMode: 420
  dnsPolicy: ClusterFirst
  tolerations:
    - key: node.kubernetes.io/not-ready
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
    - key: node.kubernetes.io/unreachable
      operator: Exists
      effect: NoExecute
      tolerationSeconds: 300
status:
  phase: Running
  conditions:
    - type: Initialized
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-10-02T22:51:05Z'
    - type: Ready
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-10-02T22:51:32Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [pingfederate]'
    - type: ContainersReady
      status: 'False'
      lastProbeTime: null
      lastTransitionTime: '2023-10-02T22:51:32Z'
      reason: ContainersNotReady
      message: 'containers with unready status: [pingfederate]'
    - type: PodScheduled
      status: 'True'
      lastProbeTime: null
      lastTransitionTime: '2023-10-02T22:51:05Z'
  hostIP: 192.168.126.11
  podIP: 10.217.0.66
  podIPs:
    - ip: 10.217.0.66
  startTime: '2023-10-02T22:51:05Z'
  containerStatuses:
    - restartCount: 2
      started: false
      ready: false
      name: pingfederate
      state:
        terminated:
          exitCode: 143
          reason: Error
          startedAt: '2023-10-02T22:51:28Z'
          finishedAt: '2023-10-02T22:51:32Z'
          containerID: >-
            cri-o://5e3b1f592f267471dd78556d06be8c6394f02adefeb9f8af7ee88db0532a8c11
      imageID: >-
        image-registry.openshift-image-registry.svc:5000/pingfederate/pingfederate@sha256:491c667f1223509c91fc5f95296989a746db086f1f368a42b4c02f1a58a3c70f
      image: >-
        image-registry.openshift-image-registry.svc:5000/pingfederate/pingfederate@sha256:491c667f1223509c91fc5f95296989a746db086f1f368a42b4c02f1a58a3c70f
      lastState:
        terminated:
          exitCode: 143
          reason: Error
          startedAt: '2023-10-02T22:51:12Z'
          finishedAt: '2023-10-02T22:51:16Z'
          containerID: >-
            cri-o://97966c8d85dee6a3af5bb481b0fc593fd620ade3c7f23e5fdf9ba1a7640be200
      containerID: 'cri-o://5e3b1f592f267471dd78556d06be8c6394f02adefeb9f8af7ee88db0532a8c11'
  qosClass: BestEffort

**Comment by ADAMSRD** [comment]
This is what the mount path looks like in OpenShift outside of the YAML:

![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/19368683/f84afca2-bedb-4422-ad11-ebe89961e51e)

**Comment by ADAMSRD** [comment]
Is there a way to confirm that the /opt/in folder is being mounted properly?  And a way to confirm /opt/in is being copied over to /opt/out?

I might be able to /bin/bash into the container and look for it but it goes into crashloopback so fast I'm having a hard time.

**Comment by ADAMSRD** [comment]
OK, I found where OpenShift allows you to debug a container in flight and was able to grab this.  It appears that the /opt/in folder is not being copied over to the /opt/out folder.

![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/19368683/ebaedace-fa8a-4908-9669-cc54dd4f609d)

**Comment by ADAMSRD** [comment]
digging deeper...  it appears that pingfederate.lic is being mounted as a directory not a file.  

![image](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/19368683/f450715d-5b67-402e-9e28-9dcf9db46a21)

**Comment by ADAMSRD** [comment]
Success!!

Found clues in: https://github.com/kubernetes/kubernetes/issues/62156

I renamed the Secret to pingfederate.lic instead of pingfederate-license, updated the YAML to the new name and it works now.

      volumes:
        - name: pingfederate-license-volume
          secret:
            secretName: pingfederate.lic
            defaultMode: 420

          env:
            - name: PING_IDENTITY_ACCEPT_EULA
              value: 'YES'

          volumeMounts:
            - name: pingfederate-license-volume
              mountPath: /opt/in/instance/server/default/conf/pingfederate.lic
              subPath: pingfederate.lic

**Comment by ADAMSRD** [comment]
proceeding to close.  I hope these notes help others.
