### ISSUE TITLE
F Secure android reporting pingid as malware 

### ISSUE THREAD

**Issue by juhalaukkanen** [pingidentity/pingidentity-devops-getting-started#526]
F secure android app version 21.1.8223678 reports pingid as potentially unwanted app. Please see the attached pictures.

![Screenshot_20231220-120542](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/5962226/cca296bc-9a10-44af-b547-faa9bfaad60b)

![Screenshot_20231220-120545](https://github.com/pingidentity/pingidentity-devops-getting-started/assets/5962226/c27865d9-5847-4a6a-af88-05f4dcbfc714)

**Comment by tomachi** [comment]
@juhalaukkanen this issue is not related to this project.
For anything related to the PingID application for Android, feel free to contact us through the Play Store support (playstore@pingidentity.com).

**Comment by PingDavidR** [comment]
Thanks @tomachi .  I'll close out this ticket as this is pursued elsewhere.
