### ISSUE TITLE
build problem on Ping Fedare - pingidentity-docker-builds project

### ISSUE THREAD

**Issue by nunesigor** [pingidentity/pingidentity-devops-getting-started#557]
Ping Docker build scripts is failing on build Ping federate container.

To reproduce it:
1- Download the latest Ping Federate zip installation file.
2- Clone the pingidentity-docker-builds repository in your local machine
3- Move the zip installation to folder pingfederate/tmp inside the repository and rename the file to produt.zip
4- on folder ci_scripts run the file serial_build.sh passing the parameters version (-v) shim (-s) and jvm (-j) like example below:
./ci_scripts/serial_build.sh -p pingfederate -v 12.1.3 -s alpine:3.20.3 -j al11
5- See the error after create ping base container.

Expected result
Creation of 4 containers: base, commom, jvm and ping federate

Error log below:
./pingidentity-docker-builds$ ./ci_scripts/serial_build.sh -p pingfederate -v 12.1.3 -s alpine:3.20.3 -j al11
################################################################################
#           Cleaning containers and images ( CI_TAG = master-ab36 )            #
################################################################################
Deleted Images:
untagged: pingidentity/pingbase:master-ab36-x86_64
deleted: sha256:ecbb6acd03a26c9295e1b06bdb381334b17cf7c7e0160f28cb02c672662692e2

Deleted build cache objects:
w1kjyvp44xklf32isempajqej
jykjc82dp8frarskr5nsxmgn1
hwuuzz4s66npjj9kqbf3o7j2d
p6pat2fvwwr1yhsjm5g7bsqjq
tpejhtmqww2rj7dgdv151mp63
73gktmu6r5hmidz8jvdofceot
kc7bd8js8hr6slsptm8qf7j6d
an05v3f0kgi0ey3k3ncgfgn05
xukrrgj3nle52ro9mtgen9nx9
i0i8kqgrlk7a7pyvq0riwx62d
53zmkyc8vov2o93iz9n7tksak
rd5dnvrkmf5ws1dse43s0cya1
pfm8bzbpztmuaj7nx8lm4n28k
bzxo0lcyql0tykfye8v718b2g

Total reclaimed space: 145.3kB
################################################################################
#                            LOCAL FOUNDATION BUILD                            #
################################################################################
################################################################################
#                             Building PING COMMON                             #
################################################################################
[+] Building 2.4s (7/12)                                                                                                                                                       docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                     0.1s
 => => transferring dockerfile: 1.28kB                                                                                                                                                   0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 17)                                                                                                          0.1s
 => WARN: InvalidDefaultArgInFrom: Default value for ARG ${DEPS}alpine:${LATEST_ALPINE_VERSION} results in empty or invalid base image name (line 17)                                    0.1s
 => [internal] load metadata for docker.io/library/alpine:3.20.3                                                                                                                         1.1s
 => [auth] library/alpine:pull token for registry-1.docker.io                                                                                                                            0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [product-staging 1/5] FROM docker.io/library/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d                                                   0.6s
 => => resolve docker.io/library/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d                                                                   0.1s
 => => sha256:33735bd63cf84d7e388d9f6d297d348c523c044410f553bd878c6d7829612735 528B / 528B                                                                                               0.0s
 => => sha256:91ef0af61f39ece4d6710e465df5ed6ca12112358344fd51ae6a3b886634148b 1.47kB / 1.47kB                                                                                           0.0s
 => => sha256:43c4264eed91be63b206e17d93e75256a6097070ce643c5e8f0379998b44f170 3.62MB / 3.62MB                                                                                           0.2s
 => => sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d 1.85kB / 1.85kB                                                                                           0.0s
 => => extracting sha256:43c4264eed91be63b206e17d93e75256a6097070ce643c5e8f0379998b44f170                                                                                                0.1s
 => [internal] load build context                                                                                                                                                        0.3s
 => => transferring context: 121.70kB                                                                                                                                                    0.2s
 => ERROR [product-staging 2/5] RUN apk --no-cache --update add gnupg                                                                                                                    0.4s
------
 > [product-staging 2/5] RUN apk --no-cache --update add gnupg:
0.290 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
0.339 283B9207007F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
0.340 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
0.340 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
0.369 283B9207007F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
0.370 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
0.370 ERROR: unable to select packages:
0.370   gnupg (no such package):
0.370     required by: world[gnupg]
------

 2 warnings found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 17)
 - InvalidDefaultArgInFrom: Default value for ARG ${DEPS}alpine:${LATEST_ALPINE_VERSION} results in empty or invalid base image name (line 17)
Dockerfile:26
--------------------
  24 |
  25 |     # Get gnupg for get-product-bits.sh
  26 | >>> RUN apk --no-cache --update add gnupg
  27 |
  28 |     # Get public signing keys for Tini
--------------------
ERROR: failed to solve: process "/bin/sh -c apk --no-cache --update add gnupg" did not complete successfully: exit code: 1
################################################################################
#                          Building PING DATA COMMON                           #
################################################################################
[+] Building 0.9s (3/3) FINISHED                                                                                                                                               docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                     0.1s
 => => transferring dockerfile: 1.01kB                                                                                                                                                   0.0s
 => WARN: InvalidDefaultArgInFrom: Default value for ARG ${REGISTRY}/pingcommon:${GIT_TAG}-${ARCH} results in empty or invalid base image name (line 21)                                 0.1s
 => ERROR [internal] load metadata for docker.io/pingidentity/pingcommon:master-ab36-x86_64                                                                                              0.7s
 => [auth] pingidentity/pingcommon:pull token for registry-1.docker.io                                                                                                                   0.0s
------
 > [internal] load metadata for docker.io/pingidentity/pingcommon:master-ab36-x86_64:
------

 1 warning found (use docker --debug to expand):
 - InvalidDefaultArgInFrom: Default value for ARG ${REGISTRY}/pingcommon:${GIT_TAG}-${ARCH} results in empty or invalid base image name (line 21)
Dockerfile:21
--------------------
  19 |
  20 |     # The final image
  21 | >>> FROM ${REGISTRY}/pingcommon:${GIT_TAG}-${ARCH}
  22 |     COPY [ "/opt/","/opt/"]
  23 |
--------------------
ERROR: failed to solve: pingidentity/pingcommon:master-ab36-x86_64: failed to resolve source metadata for docker.io/pingidentity/pingcommon:master-ab36-x86_64: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
################################################################################
#               Building pingjvm for JDK al11 for alpine:3.20.3                #
################################################################################
[+] Building 1.3s (7/8)                                                                                                                                                        docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                     0.1s
 => => transferring dockerfile: 307B                                                                                                                                                     0.0s
 => WARN: FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)                                                                                                           0.1s
 => WARN: InvalidDefaultArgInFrom: Default value for ARG ${DEPS}${SHIM} results in empty or invalid base image name (line 5)                                                             0.1s
 => [internal] load metadata for docker.io/library/alpine:3.20.3                                                                                                                         0.6s
 => [internal] load .dockerignore                                                                                                                                                        0.1s
 => => transferring context: 53B                                                                                                                                                         0.0s
 => [internal] load build context                                                                                                                                                        0.1s
 => => transferring context: 6.78kB                                                                                                                                                      0.0s
 => CACHED [jvm-staging 1/3] FROM docker.io/library/alpine:3.20.3@sha256:beefdbd8a1da6d2915566fde36db9db0b524eb737fc57cd1367effd16dc0d06d                                                0.0s
 => [jvm-staging 2/3] COPY [build-jvm.sh,/]                                                                                                                                              0.1s
 => ERROR [jvm-staging 3/3] RUN ["/build-jvm.sh"]                                                                                                                                        0.3s
------
 > [jvm-staging 3/3] RUN ["/build-jvm.sh"]:
0.224 No java found. Pulling down Liberica Standard JDK for Alpine Linux x86_64...
0.229 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/main/x86_64/APKINDEX.tar.gz
0.289 28CB0839437F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
0.290 fetch https://dl-cdn.alpinelinux.org/alpine/v3.20/community/x86_64/APKINDEX.tar.gz
0.290 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/main: Permission denied
0.318 28CB0839437F0000:error:0A000086:SSL routines:tls_post_process_server_certificate:certificate verify failed:ssl/statem/statem_clnt.c:2091:
0.319 WARNING: fetching https://dl-cdn.alpinelinux.org/alpine/v3.20/community: Permission denied
0.319 ERROR: unable to select packages:
0.319   binutils (no such package):
0.319     required by: world[binutils]
0.319   curl (no such package):
0.319     required by: world[curl]
0.322 /build-jvm.sh: eval: line 77: curl: not found
0.323 sha1sum: can't open '/tmp/tmp.hBiNff/jdk.tgz': No such file or directory
0.323 ERROR: JDK tar file checksum does not match. Expected: 75c3d8caa4339f35c5df8812040802eb6498426d Actual:
------

 2 warnings found (use docker --debug to expand):
 - InvalidDefaultArgInFrom: Default value for ARG ${DEPS}${SHIM} results in empty or invalid base image name (line 5)
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 5)
Dockerfile:13
--------------------
  11 |     COPY ["build-jvm.sh","/"]
  12 |
  13 | >>> RUN ["/build-jvm.sh"]
  14 |
  15 |     FROM scratch
--------------------
ERROR: failed to solve: process "/build-jvm.sh" did not complete successfully: exit code: 93
################################################################################
#                              Building pingbase                               #
################################################################################
[+] Building 0.3s (6/6) FINISHED                                                                                                                                               docker:default
 => [internal] load build definition from Dockerfile                                                                                                                                     0.0s
 => => transferring dockerfile: 9.62kB                                                                                                                                                   0.0s
 => WARN: NoEmptyContinuation: Empty continuation line (line 213)                                                                                                                        0.0s
 => WARN: SecretsUsedInArgOrEnv: Do not use ARG or ENV instructions for sensitive data (ENV "PING_IDENTITY_DEVOPS_KEY_REDACT") (line 33)                                                 0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [internal] load build context                                                                                                                                                        0.0s
 => => transferring context: 107B                                                                                                                                                        0.0s
 => [1/2] WORKDIR /opt                                                                                                                                                                   0.0s
 => [2/2] COPY [./license.txt,/licenses/]                                                                                                                                                0.0s
 => exporting to image                                                                                                                                                                   0.0s
 => => exporting layers                                                                                                                                                                  0.0s
 => => writing image sha256:a498a59527a6d96746291266660241abb0b0861139288212f4febcb65649a7c8                                                                                             0.0s
 => => naming to docker.io/pingidentity/pingbase:master-ab36-x86_64                                                                                                                      0.0s
 IMAGE                                                |   DURATION|  RESULT
❌ pingjvm:al11-alpine_3.20.3                          |          4|    FAIL
✔ pingbase                                            |          3|    PASS
Total duration: 16s

**Comment by PingDavidR** [comment]
@nunesigor I just re-ran your command:

 `./ci_scripts/serial_build.sh -p pingfederate -v 12.1.3 -s alpine:3.20.3 -j al11` 

after grabbing the 12.1.3 zip and renaming it as we are instructed to do.  Attached is the output from my run, which was successful.  

It's looking like you may have hit a transient error around the **gnupg** package as I indicated above. 

In hindsight, I probably should have used a different branch name that didn't include the text "build-fail" in it as all of my images ended up with that tag ;)

Would you mind trying again and reporting back?
[build_log.txt](https://github.com/user-attachments/files/17100241/build_log.txt)

**Comment by PingDavidR** [comment]
@nunesigor We are going to close this ticket at this time.  If you have any further issues, feel free to reach out again, and we will help in any way possible.
