### ISSUE TITLE
Frontdoor entry process for DevOps.pingidentity.com is broken

### ISSUE THREAD

**Issue by tachyonik** [pingidentity/pingidentity-devops-getting-started#564]
**Describe the bug**
I just created an account using my work email address. After numerous attempts at email verification and password resets, now that the password is accepted after sign-in, I am unable to proceed after login to anywhere else in the support portal or devops website. All I am facing is an error page which says: "We can't log you in because of an issue with single sign-on. Contact your Salesforce admin for help."

**To Reproduce**
1. Go to 'devops.pingidentity.com'
2. Click on 'Sign On'
3. Enter the credentials 
<img width="533" alt="sign-on-error" src="https://github.com/user-attachments/assets/887ed384-e286-4052-9637-bcb0033a7939">

**Expected behavior**
I should be able to login and access the community page as described in the instructions here: https://devops.pingidentity.com/how-to/devopsRegistration/.

**Screenshots**
<img width="533" alt="sign-on-error" src="https://github.com/user-attachments/assets/887ed384-e286-4052-9637-bcb0033a7939">

**Environment:**
 - DevOps.pingidentity.com website

**Additional Info**
NA

**Comment by PingDavidR** [comment]
Thanks for reaching out, @tachyonik.

I appreciate your frustration with this occurrence.  However, as indicated, the issue at hand appears to involve the account in Salesforce, and this team does not have insight internally to handle the problem.  Your best bet is to reach out to your sales representative or customer service contact at Ping for guidance and help in getting this resolved.

You can also engage at the [support portal](https://support.pingidentity.com/s/) or perhaps the [community forums](https://support.pingidentity.com/s/community-home) as well.
