### ISSUE TITLE
older versions unable to be built

### ISSUE THREAD

**Issue by iwarapter** [pingidentity/pingidentity-devops-getting-started#7]
Hi,

I'm unable to build a container with a slightly older version of a product:

docker build --build-arg VERSION=5.1.1 -t pingidentity/pingaccess:5.1.1 .

This resolves the URL https://s3.amazonaws.com/gte-bits-repo/pingaccess-5.1.1.zip which presents:

```xml
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>6E15465AC3BFB8A8</RequestId>
<HostId>
ktG8hMr+16SeByBzJocLudePtLBIfUE/ZVxh7Wb7Ttq6+eqIRlLJnhiew1zyobeXDm11xrV3/uA=
</HostId>
</Error>
```

Are the product distributions available within the S3 bucket?

**Comment by arnaudlacour** [comment]
We're working towards supporting all product versions .2 and up at the moment.
The ability to build multiple versions is only a facility to continue building .2 when a more docker-friendly .3 release is out in June '19.

We patched run.sh to be able to run the products in their current incarnation but we are not looking at back-porting it .1
