### ISSUE TITLE
Kubernetes pingdataconsole protocol mismatch 

### ISSUE THREAD

**Issue by rlewkowicz** [pingidentity/pingidentity-devops-getting-started#75]
**Describe the bug**
Port exposed is non secure, port routed to is secure. 

**To Reproduce**
`./apply -u directory` from the Kubernetes stuff. Pingdataconsole is not accessible via lb do to a protocol mismatch. 

I submitted a easy little pull for this:
https://github.com/pingidentity/pingidentity-devops-getting-started/pull/74

**Comment by arnaudlacour** [comment]
this issue is now resolved, thank you for reporting it.
