### ISSUE TITLE
build.sh doesn't exist for Minikube 

### ISSUE THREAD

**Issue by rarean** [pingidentity/pingidentity-devops-getting-started#76]
**Describe the bug**
README for minikube references `./build.sh` to build images. However that file does not exist under the minikube dir

**To Reproduce**
1. Go to 'pingidentity-devops-getting-started/tree/master/20-kubernetes/cloud/minikube'
2. View Readme
4. See reference to 'build images locally with `./build.sh`'

**Expected behavior**
reference to file in current directory should exist

**Additional Info**
I believe the `build.sh` being references is in a different repo, and should be a link to `pingidentity-docker-builds` repo

**Comment by samir-gandhi** [comment]
Thanks for pointing out this issue. These were actually old docs from before our images were public. I've archived this section of docs.
